package Configs;

public interface AchievementEventTableConfig {

    String ACHIEVEMENT_EVENT_TABLE_NAME = "achievement_events";

    String ACHIEVEMENT_EVENT_TABLE_COLUMN_1_ID = "ID";
    String ACHIEVEMENT_EVENT_TABLE_COLUMN_2_ACHIEVEMENT_ID = "ACHIEVEMENT_ID";
    String ACHIEVEMENT_EVENT_TABLE_COLUMN_3_USER_ID = "USER_ID";
    String ACHIEVEMENT_EVENT_TABLE_COLUMN_4_ACHIEVE_DATE = "ACHIEVE_DATE";

}
