package Configs;

public interface BlogsTableConfig {

    String BLOGS_TABLE_COLUMN_1_ID = "ID";
    String BLOGS_TABLE_COLUMN_2_TITLE = "TITLE";
    String BLOGS_TALBE_COLUMN_3_CATEGORY = "CATEGORY";
    String BLOGS_TABLE_COLUMN_3_SMALL_DESCRIPTION = "SMALL_DESCRIPTION";
    String BLOGS_TABLE_COLUMN_4_FULL_DESCRIPTION = "FULL_DESCRIPTION";
    String BLOGS_TABLE_COLUMN_4_ICON_URL = "COVER_URL";
    String BLOGS_TABLE_COLUMN_6_COMMENT = "COMMENT";
    String BLOGS_TABLE_COLUMN_7_AUTHOR_ID = "AUTHOR_ID";
    String BLOGS_TABLE_COLUMN_8_CREATION_DATE = "PUBLISHING_DATE";

}
