package Configs;

public interface ChallengesTableConfig {

    String CHALLENGES_TABLE_NAME = "challenges";

    String CHALLENGES_TABLE_COLUMN_1_ID = "ID";
    String CHALLENGES_TABLE_COLUMN_2_QUIZ_ID = "QUIZ_ID";
    String CHALLENGES_TABLE_COLUMN_3_CHALLENGER_USER_ID = "CHALLENGER_USER_ID";
    String CHALLENGES_TABLE_COLUMN_4_CHALLENGED_USER_ID = "CHALLENGED_USER_ID";
    String CHALLENGES_TABLE_COLUMN_5_CHALLENGER_QUIZ_EVENT_ID = "CHALLENGER_QUIZ_EVENT_ID";
    String CHALLENGES_TABLE_COLUMN_6_CHALLENGED_QUIZ_EVENT_ID = "CHALLENGED_QUIZ_EVENT_ID";
    String CHALLENGES_TABLE_COLUMN_7_IS_FINISHED = "IS_FINISHED";
    String CHALLENGES_TABLE_COLUMN_8_WINNER_USER_ID = "WINNER_ID";
    String CHALLENGES_TABLE_COLUMN_9_CHALLENGING_DATE = "CHALLENGING_DATE";
    String CHALLENGES_TABLE_COLUMN_10_ACCEPTING_DATE = "ACCEPTING_DATE";

}