package Configs;

public interface FriendshipsTableConfig {

    String FRIENDSHIPS_TABLE_NAME = "friendship";

    String FRIENDSHIPS_TABLE_COLUMN_1_ID = "ID";
    String FRIENDSHIPS_TABLE_COLUMN_2_FIRST_FRIEND_ID = "FIRST_FRIEND_ID";
    String FRIENDSHIPS_TABLE_COLUMN_3_SECOND_FRIEND_ID = "SECOND_FRIEND_ID";
    String FRIENDSHIPS_TABLE_COLUMN_4_MAKE_FRIEND_DATE = "MAKE_FRIEND_DATE";

}
