package Configs;

public interface FriendshipsTableConfig {

    String FRIENDSHIP_TABLE_NAME = "friendship";

    String FRIENDSHIP_TABLE_COLUMN_1_ID = "ID";
    String FRIENDSHIP_TABLE_COLUMN_2_FIRST_FRIEND_ID = "FIRST_FRIEND_ID";
    String FRIENDSHIP_TABLE_COLUMN_3_SECOND_FRIEND_ID = "SECOND_FRIEND_ID";
    String FRIENDSHIP_TABLE_COLUMN_4_MAKE_FRIEND_DATE = "MAKE_FRIEND_DATE";
    
}
