package Configs;

public interface FriendRequestsTableConfig {

    String FRIEND_REQUESTS_TABLE_NAME = "friend_requests";

    String FRIEND_REQUESTS_TABLE_COLUMN_1_ID = "ID";
    String FRIEND_REQUESTS_TABLE_COLUMN_2_SENDER_ID = "SENDER_ID";
    String FRIEND_REQUESTS_TABLE_COLUMN_3_RECEIVER_ID = "RECEIVER_ID";
    String FRIEND_REQUESTS_TABLE_COLUMN_4_SENDING_DATE = "SENDING_DATE";
    String FRIEND_REQUESTS_TABLE_COLUMN_5_RECEIVING_DATE = "RECEIVING_DATE";
    String FRIEND_REQUESTS_TABLE_COLUMN_6_IS_RECEIVED = "IS_RECEIVED";
    String FRIEND_REQUESTS_TABLE_COLUMN_7_IS_ACCEPTED = "IS_ACCEPTED";

}
