package Configs;

public interface QuestionTableConfig {

    /* question's table */
    String QUESTION_TABLE_COLUMN_1_ID = "ID";   // int
    String QUESTION_TABLE_COLUMN_2_TYPE = "TYPE";   // int
    String QUESTION_TABLE_COLUMN_3_IS_AUTO_GRADED = "IS_AUTO_GRADED";   // boolean
    String QUESTION_TABLE_COLUMN_4_MAX_SCORE = "MAX_SCORE"; // double
    String QUESTION_TABLE_COLUMN_5_HEADER_STATEMENT = "HEADER_STATEMENT"; // string
    String QUESTION_TABLE_COLUMN_6_COMMENT = "COMMENT"; // string
    String QUESTION_TABLE_COLUMN_7_SOURCE = "SOURCE";   // string
    String QUESTION_TABLE_COLUMN_8_CREATION_DATE = "CREATION_DATE"; // Date
    String QUESTION_TABLE_COLUMN_9_QUIZ_ID = "QUIZ_ID"; // int
    String QUESTION_TABLE_COLUMN_10_TEXT_STATEMENT = "TEXT_STATEMENT"; // blob || BigText
    String QUESTION_TABLE_COLUMN_11_IS_PICTURE_QUESTION = "IS_PICTURE_QUESTION"; // boolean
    String QUESTION_TABLE_COLUMN_12_NUM_CHOICE_STATEMENTS = "NUM_CHOICE_STATEMENTS";    // int

    String QUESTION_TABLE_COLUMN_13_CHOICE_STATEMENT_0 = "CHOICE_STATEMENT_0";
    // ...
    String QUESTION_TABLE_COLUMN_28_CHOICE_STATEMENT_15 = "CHOICE_STATEMENT_15";

    String QUESTION_TABLE_COLUMN_29_TEXT_ANSWER = "TEXT_ANSWER";
    String QUESTION_TABLE_COLUMN_30_IS_PICTURE_ANSWER = "IS_PICTURE_ANSWER";

    String QUESTION_TABLE_COLUMN_31_NUM_ANSWERS = "NUM_ANSWERS";

    String QUESTION_TABLE_COLUMN_32_ANSWER_0 = "ANSWER_0";
    // ...
    String QUESTION_TABLE_COLUMN_47_ANSWER_15 = "ANSWER_15";

    String QUESTION_TABLE_ITH_CHOICE_TEXT = "CHOICE_STATEMENT_";
    String QUESTION_TABLE_ITH_ANSWER_TEXT = "ANSWER_";

}
