package Configs;

public interface QuizTableConfig {

    String QUIZ_TABLE_NAME = "quizes";

    String QUIZ_TABLE_COLUMN_1_ID = "ID";
    String QUIZ_TABLE_COLUMN_2_NAME = "NAME";
    String QUIZ_TABLE_COLUMN_3_DESCRIPTION = "DESCRIPTION";
    String QUIZ_TABLE_COLUMN_4_ICON_URL = "ICON_URL";
    String QUIZ_TABLE_COLUMN_5_MUST_SHUFFLE_QUESTIONS = "MUST_SHUFFLE_QUESTIONS";
    String QUIZ_TABLE_COLUMN_6_COMMENT = "COMMENT";
    String QUIZ_TABLE_COLUMN_7_AUTHOR_ID = "AUTHOR_ID";
    String QUIZ_TABLE_COLUMN_8_CREATION_DATE = "CREATION_DATE";
    String QUIZ_TABLE_COLUMN_9_MAX_SCORE = "MAX_SCORE";

}
