package Configs;

public interface QuizTableConfig {

    String QUIZ_TABLE_NAME = "quizzes";

    String QUIZ_TABLE_COLUMN_1_ID = "ID";
    String QUIZ_TABLE_COLUMN_2_NAME = "NAME";
    String QUIZ_TABLE_COLUMN_3_CATEGORY_ID = "CATEGORY_ID";
    String QUIZ_TABLE_COLUMN_4_DESCRIPTION = "DESCRIPTION";
    String QUIZ_TABLE_COLUMN_5_ICON_URL = "ICON_URL";
    String QUIZ_TABLE_COLUMN_6_MUST_SHUFFLE_QUESTIONS = "MUST_SHUFFLE_QUESTIONS";
    String QUIZ_TABLE_COLUMN_7_COMMENT = "COMMENT";
    String QUIZ_TABLE_COLUMN_8_AUTHOR_ID = "AUTHOR_ID";
    String QUIZ_TABLE_COLUMN_9_CREATION_DATE = "CREATION_DATE";
    String QUIZ_TABLE_COLUMN_10_MAX_SCORE = "MAX_SCORE";

}
