package Configs;

public interface UserTableConfig {

    String USERS_TABLE_NAME = "users";

    String USERS_TABLE_COLUMN_1_ID = "ID";
    String USERS_TABLE_COLUMN_2_FIRST_NAME = "FIRST_NAME";
    String USERS_TABLE_COLUMN_3_LAST_NAME = "LAST_NAME";
    String USERS_TABLE_COLUMN_4_USERNAME = "USERNAME";
    String USERS_TABLE_COLUMN_5_PASSWORD = "PASSWORD_HASH";
    String USERS_TABLE_COLUMN_6_CITY = "CITY";
    String USERS_TABLE_COLUMN_7_COUNTRY = "COUNTRY";
    String USERS_TABLE_COLUMN_8_MOBILE_NUMBER = "MOBILE_NUMBER";
    String USERS_TABLE_COLUMN_9_EMAIL = "EMAIL";
    String USERS_TABLE_COLUMN_10_BIRTH_DATE = "BIRTH_DATE";
    String USERS_TABLE_COLUMN_11_REGISTRATION_DATE = "REGISTRATION_DATE";

}
